Feature/us28 medias queries
WildCodeSchool-2024-09/JS-Nantes-P2-SeriesIsComing pull request #30
Opened 2024-11-21 15:42 UTC by JLRWOLF44

2024-11-21 16:00 UTC, Jeremy-Mrz requested changes

2024-11-21 16:00 UTC, Jeremy-Mrz commented on client/src/components/NavBar.tsx
> +            <span className="h3-text"> A propos</span>
Pourquoi avoir remplacé le `<h3>` par un `<span className="h3-text">` ?

2024-11-21 16:00 UTC, Jeremy-Mrz commented on client/src/components/NavBar.tsx
> +            <span className="h3-text">Nous contacter</span>
Même question

2024-11-22 08:40 UTC, JLRWOLF44 commented on client/src/components/NavBar.tsx
> +            <span className="h3-text"> A propos</span>
Pour répondre à ta question, je vais dire à cause de chatGpt j'ai pris la faciliter car je cherchais une solution rapide a un soucis. ET avec un peu de recherche il est vrai que j'aurais pu laisser le <h3> et lui mettre simplement une class ou bien mettre une div peut être à la place de span qui après un peu de recherche ne sert pas à grand chose.

2024-11-22 09:01 UTC, JLRWOLF44 commented on client/src/components/Navbar.css
> +/* menu deroulant */
j'ai enlever !!!

2024-11-22 09:01 UTC, JLRWOLF44 commented on client/src/components/Navbar.css
> +}
idem !!

2024-11-22 09:02 UTC, JLRWOLF44 commented on client/src/components/Navbar.css
> +
c'est fait changer avec id

2024-11-22 09:18 UTC, Jeremy-Mrz requested changes

2024-11-22 09:18 UTC, Jeremy-Mrz commented on client/src/components/NavBar.tsx
> +            <div className="h3-text"> A propos</div>
SI tu veux styliser un h3, utilises une balise `<h3>`. Pas te texte dans un `<div>` sans balise de texte

2024-11-22 09:18 UTC, Jeremy-Mrz commented on client/src/components/NavBar.tsx
> +            <div className="h3-text">Nous contacter</div>
Idem

2024-11-22 09:18 UTC, Jeremy-Mrz commented on client/src/components/NavBar.tsx
> +          <div className="h3-text">
Idem

2024-11-22 09:18 UTC, Jeremy-Mrz commented on client/src/components/Navbar.css
> +
Je vois toujours une classe & un id, as tu bien fait les changements ?

2024-11-22 10:46 UTC, Jeremy-Mrz commented on client/src/components/NavBar.tsx
> +            </div>
Tu peux mettre ta classe directement dans ton `<h3>` et supprimer le `<div>`

`<h3 className="h3-text">`

2024-11-22 10:46 UTC, Jeremy-Mrz commented on client/src/components/NavBar.tsx
> +            </div>
Idem

2024-11-22 11:02 UTC, Jeremy-Mrz approved these changes

2024-11-22 11:02 UTC, merged