Feature/us32 general filters
WildCodeSchool-2024-09/JS-Nantes-P2-SeriesIsComing pull request #38
Opened 2024-11-25 15:32 UTC by Koraltaron

2024-11-26 13:46 UTC, MrLootman requested changes

2024-11-26 13:46 UTC, MrLootman commented on client/src/pages/Favorite.tsx
> +      <p>blablabmla</p>
Ce code ne devrait pas être fusionné avec dev.

2024-11-26 13:46 UTC, MrLootman commented on client/src/utils/useFilter.tsx
Il serait bon refactoriser cette fonction, pour éviter la répétition de code autant que possible.

2024-11-26 13:46 UTC, MrLootman commented on client/src/utils/useFilter.tsx
> +      throw new Error("Nope");
Le "Nope" n'est pas un message d'erreur valide. A modifier.

2024-11-26 14:11 UTC, Koraltaron commented on client/src/pages/Favorite.tsx
> +      <p>blablabmla</p>
Tout à fait d'accord, c'est le reliquat d'une démonstration de création de page à destination de Jean-Louis ! J'ai rm mon fichier.

2024-11-26 14:14 UTC, Koraltaron commented on client/src/utils/useFilter.tsx
> +      throw new Error("Nope");
En effet ! J'ai changé l'erreur.

2024-11-26 15:51 UTC, Koraltaron commented on client/src/utils/useFilter.tsx
J'ai modifié useFilter en conséquence !

2024-11-26 16:09 UTC, Koraltaron commented
J'ai répondu aux commentaires, mis à jour ma branche et push la dernière version !

2024-11-27 08:33 UTC, MrLootman approved these changes

2024-11-27 08:33 UTC, MrLootman commented on client/src/utils/useFilter.tsx
C'est beaucoup mieux 👍

2024-11-27 08:33 UTC, merged